name: Push notification on commit of content/daily-hukumnama.json

on:
  push:
    branches:
      - "master"
    paths:
      - "./content/daily-hukumnama.json"
env:
  ONESIGNAL_APP_ID: "0ddb5f3a-df91-4d2a-bd99-0b841f86288e"

jobs:
  read_hukumnama_file:
    runs-on: ubuntu-latest
    outputs:
      hukumnama_content: ${{ steps.daily_hukumnama.outputs.content }}
    steps:
      - name: Read content/daily-hukumnama.json
        id: daily_hukumnama
        uses: juliangruber/read-file-action@v1
        with:
          path: ./content/daily-hukumnama.json

  send_onesignal_notification:
    runs-on: ubuntu-latest
    needs: read_hukumnama_file
    if: ${{ needs.read_hukumnama_file.hukumnama_content.photo != '' }}
    steps:
      - name: Send OneSignal Notification
        uses: cingh-jasdeep/onesignal-github-action@0.0.5
        with:
          apiKey: ${{ secrets.ONESIGNAL_TEST_API_KEY }}
          appId: ${{ env.ONESIGNAL_APP_ID }}
          contentsEn: "Today's Hukumnama"
          headingsEn: "Gurdwara Prabh Milne Ka Chao, Moga"
          isAndroid: true
          isIos: true
          isAnyWeb: true
          webUrl: "https://wahegurulive.com/hukumnama/today/"
