name: Push notification on commit of content/daily-hukumnama.json

on:
  push:
    branches:
      - "master"
    paths:
      - "content/daily-hukumnama.json"
env:
  ONESIGNAL_APP_ID: "0ddb5f3a-df91-4d2a-bd99-0b841f86288e"

jobs:
  read_hukumnama_file:
    runs-on: ubuntu-latest
    outputs:
      hukumnama_photo_url: ${{steps.daily_hukumnama_photo.outputs.prop}}
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master

      - name: Read content/daily-hukumnama.json for photo
        id: daily_hukumnama_photo
        uses: notiz-dev/github-action-json-property@release
        with:
          path: "content/daily-hukumnama.json"
          prop_path: "photo"

      - run: echo ${{steps.daily_hukumnama_photo.outputs.prop}}

  send_onesignal_notification:
    runs-on: ubuntu-latest
    needs: read_hukumnama_file
    if: ${{ needs.read_hukumnama_file.hukumnama_photo_url != '' }}
    steps:
      - name: Send OneSignal Notification
        uses: cingh-jasdeep/onesignal-github-action@0.0.5
        with:
          apiKey: ${{ secrets.ONESIGNAL_TEST_API_KEY }}
          appId: ${{ env.ONESIGNAL_APP_ID }}
          contentsEn: "Today's Hukumnama"
          headingsEn: "Gurdwara Prabh Milne Ka Chao, Moga"
          isAndroid: true
          isIos: true
          isAnyWeb: true
          webUrl: "https://wahegurulive.com/hukumnama/today/"
