name: Push notification on commit of content/daily-hukumnama.json

on:
  push:
    branches:
      - "master"
    paths:
      - "content/daily-hukumnama.json"
env:
  ONESIGNAL_APP_ID: "0ddb5f3a-df91-4d2a-bd99-0b841f86288e"

jobs:
  read_hukumnama_file:
    runs-on: ubuntu-latest
    outputs:
      hukumnama_photo_url: ${{steps.daily_hukumnama_photo.outputs.prop}}
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master

      - name: Read content/daily-hukumnama.json for photo
        id: daily_hukumnama_photo
        uses: thiagomoreirac/github-action-json-property@v0.1.3-beta
        with:
          path: "content/daily-hukumnama.json"
          prop_path: "photo"
        continue-on-error: true

  send_onesignal_notification:
    runs-on: ubuntu-latest
    needs: read_hukumnama_file
    if: ${{ needs.read_hukumnama_file.outputs.hukumnama_photo_url != '' }}
    steps:
      - name: Send OneSignal Notification
        run: |
          curl --include \
              --request POST \
              --header "Content-Type: application/json; charset=utf-8" \
              --header "Authorization: Basic NjE5OThjNDktMzczNy00MjAzLTg4NmUtM2Q4ZGI1MzBiNGVk" \
              --data-binary "{\"app_id\": \"0ddb5f3a-df91-4d2a-bd99-0b841f86288e\",
          \"contents\": {\"en\": \"Today's Hukumnama\"},
          \"headings\": {\"en\": \"Gurdwara Prabh Milne Ka Chao, Moga\"},
          \"isAndroid\": true,
          \"isIos\": true,
          \"isAnyWeb\": true,
          \"included_segments\": [\"Subscribed Users\"]}" \
              https://onesignal.com/api/v1/notifications
